<!-- Page Ajouter un évènement -->
<section class="content">
    <h1>Ajouter un évènement</h1>
    <p>Pour ajouter une évènement,
        merci de remplir le formulaire ci-dessous.</p>
</section>
<form class="content space" method="post" enctype="multipart/form-data">
    <div class="form_group">
        <label for="date">Date</label><input type="date" id="date" name="date" value="<?= $date ?>" required>
    </div>
    <div class="form_group">
        <label for="type">Type d'évènement</label><input type="text" id="type" name="type" required>
    </div>
    <div class="form_group">
        <label for="place">Lieu de l'évènement</label><input type="text" id="place" name="place" required>
    </div>
    <div class="form_group">
        <label for="who">Organisateur</label><input type="text" id="who" name="who" required>
    </div>
    <div class="form_group upload_file">
        <input type="file" id="reservation" class="input_file" name="reservation" accept=".pdf"
            data-multiple-caption="{count} files selected"><label for="reservation" class="btn_red label_file"><i
                class="fas fa-file-upload"></i>
            <p>Affiche ou Reservation</p>
        </label>
        <input type="file" id="playlist" class="input_file" name="playlist" accept=".pdf"><label for="playlist"
            class="btn_red label_file"><i class="fas fa-file-upload"></i>
            <p>Playlist</p>
        </label>
    </div>
    <div class="btns">
        <input type="submit" value="Envoyer" class="btn_red"> <input type="reset" value="Effacer" class="btn_gray">
    </div>
</form>