<!-- Page Modification de Questions FAQ -->
<section class="content space">
    <h1>Modifier une question</h1>
    <p>Pour modifier une question, merci de remplir le formulaire ci-dessous.</p>

    <form class="content space" method="post" enctype="multipart/form-data">
        <div class="form_group">
            <label for="question">Question</label><input type="text" name="question" id="question"
                value="<?= $faq['question'] ?>">
        </div>
        <div class="form_group">
            <label for="answer">Réponse</label><textarea name="answer" id="answer"><?= $faq['answer'] ?></textarea>
        </div>
        <?php if (isset($faq['id_img'])): ?>
        <img src="<?= $path ?>img/faq/<?= $img['name'] ?>.<?= $img['extension'] ?>" alt="<?= $img['alt'] ?>">
        <?php endif ?>
        <div class="form_group upload_file">
            <input type="file" id="img" class="input_file" name="img" accept="image/jpg,image/png,image/gif"
                data-multiple-caption="{count} files selected"><label for="img" class="btn_red label_file"><i
                    class="fas fa-file-upload"></i>
                <!-- Si l'image existe -->
                <?php if (isset($faq['id_img'])): ?>
                <p><?= $img['name'] ?>.<?= $img['extension'] ?></p>
                <?php else : ?>
                <p>Image</p>
                <?php endif ?>
            </label>
        </div>
        <div class="form_group">
            <label for="alt_img">Description de l'image</label><input type="text" name="alt_img" id="alt_img"
                value="<?= $img['alt'] ?>">
        </div>
        <div class="btns">
            <input type="submit" value="Envoyer" class="btn_red"> <input type="reset" value="Effacer" class="btn_gray">
        </div>
    </form>
</section>