<!-- Page d'accueil -->
<section id="introActu">
    <div id="intro_img">
        <div id="intro">
            <h1>Cécile Haillot</h1>
            <p><?= htmlspecialchars($intro['contents']) ?></p>
        </div>
    </div>
    <div class="info" id="actu"><?= htmlspecialchars($actu['contents']) ?></div>
</section>
<section class="content flex">
    <!-- Pour chaque cours -->
    <?php foreach ($carte_cours as $cours): ?>
    <article class="card">
        <h2><?= htmlspecialchars($cours['city']) ?></h2>
        <p><?= htmlspecialchars($cours['text_card']) ?></p>
        <a href="<?= $path ?>controllers/classes.php?id=<?= intval($cours['id']) ?>">Voir le cours</a>
    </article>
    <?php endforeach ?>
</section>
<div class="p_border space">
    <p class="content p_index"><?= nl2br($p1['contents']) ?></p>
</div>
<iframe class="space"
    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2712.4242081291836!2d-1.7271536844835944!3d47.16913042608859!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4805968301eff4cb%3A0xc3d09f748f343434!2sLes%20Amis%20des%20Ecoles%20La%C3%AFques!5e0!3m2!1sfr!2sfr!4v1585733796978!5m2!1sfr!2sfr"></iframe>

<div class="p_border space">
    <p class="content p_index">
        <img class="f_right"
            src="<?=$path ?>img/<?= $imgDiplome['name'] ?>.<?= $imgDiplome['extension'] ?>"
            alt="<?= $imgDiplome['alt'] ?>"><?= nl2br($p2['contents']) ?></p>
    <div class="clear"></div>
</div>